In [1]:
import numpy as np
import torch
import plotly.express as px
import plotly.graph_objects as go

### Overflow and Underflow

In [10]:
# underflow
# the numbers near to zero are rounded to zero

In [11]:
zeros = torch.zeros(3, 3)

In [12]:
torch.log(zeros)

tensor([[-inf, -inf, -inf],
        [-inf, -inf, -inf],
        [-inf, -inf, -inf]])

In [39]:
# overflow
# numbers with large infiniate magnitude are approximate as inf or -inf

In [41]:
torch.exp(torch.tensor([1000]))

tensor([inf])

In [46]:
small_number = 1e-324

In [47]:
small_number

0.0

In [48]:
underflow = small_number / 10
print(f"Underflow result: {underflow}")

Underflow result: 0.0


In [49]:
x = torch.tensor([1000.0, 1001.0, 1002.0])

In [55]:
softmax = torch.exp(x) / torch.sum(torch.exp(x))
print(f"Softmax function (with overflow): {softmax}")

Softmax function (with overflow): tensor([nan, nan, nan])


In [58]:
max_x = torch.max(x)
stable_softmax = torch.exp(x - max_x) / torch.sum(torch.exp(x - max_x))
print(f"Stabled Softmax function: {stable_softmax}")

Stabled Softmax function: tensor([0.0900, 0.2447, 0.6652])


### Poor Conditioning

In [59]:
# how a function changes with respect to small change in input

In [60]:
A = torch.tensor([[1.0, 2.0], [2.0, 1.0]])
b = torch.tensor([3.0, 3.0])

In [62]:
x = torch.linalg.solve(A, b)

In [63]:
x

tensor([1., 1.])

In [64]:
A = torch.tensor([[1.0, .0], [2.0, 1.0001]])
b = torch.tensor([3.0, 3.0001])

In [65]:
torch.linalg.solve(A, b)

tensor([1., 1.])