In [1]:
import numpy
import plotly.express as px
import torch
import matplotlib.pyplot as plt
%matplotlib inline

### 3.3 Probability Distribution

#### 3.3.1 Discreate Variable and Probability Mass Function

In [3]:
# Probability Distribution over discreate variable is called Probability Mass Function
# Mainly Denoted by P(x = x) | P(x) and P(y = y) | P(y) and P(x=x, y=y) == P(x, y)
# 1) P(x = x) = 1 means x is certain.  2) P(x = x) = 0 means is impossible.

In [3]:
dis_var = torch.tensor([0, 1, 1, 2, 3, 4, 5, 6, 7, 8])
dis_var, dis_var.nelement()

(tensor([0, 1, 1, 2, 3, 4, 5, 6, 7, 8]), 10)

In [11]:
# target value to check
target = 1

occurance = torch.sum(dis_var == target).item()

total_elements = dis_var.nelement()

prob = occurance / total_elements

# Check for probability validity
if prob < 0.0:
    raise ValueError("Probability of less than 0 is impossible for an event.")
elif prob > 1.0:
    raise ValueError("Probability greater than 1 is impossible for a single event.")
else:
    print(f"The probability of {target} in dis_var: {dis_var.tolist()}: {prob}")
print(prob)

The probability of 1 in dis_var: [0, 1, 1, 2, 3, 4, 5, 6, 7, 8]: 0.2
0.2


In [12]:
# 1) single discrete random variable x with k different states. We can place a uniform distribution over x.
# 2) the Probability Mass Function is 1 / k = P(x = x_i) for all i. (k is positive integer)
# 3) sum(P(x = x_i)) == sum(1 / k) == k / k == 1 the distribution is properly normalised.

In [18]:
event = 1
x = torch.arange(1, 11)
k = x.nelement()
prob_mass_func = event / k
prob_mass_func

0.1

In [19]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
k / k

1.0

In [29]:
event = 4

occurance = torch.sum(event == x).item()

total_event = x.nelement()

prob = occurance / total_event
prob

0.1

#### 3.3.2 Continous Variable and Probability Density Function

In [30]:
# On continous random variables we discribe the probability distribution using probability density function rather than Probability Mass Function.
# the domain of P must be all possible states of x

In [31]:
con_var = torch.arange(10, dtype=torch.float32)
con_var

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
# so the p(x) >= 0. Note that we do not require p(x) <= 1
k = con_var.nelement()
# x / k must require greater value than 0 and not limited to 1 it can be greater than 1.
print(f"All possible states in con_var:\n {con_var}\n")
print(f"Number of all possible states in con_var: \n{con_var.nelement()}\n")

All possible states in con_var:
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Number of all possible states in con_var: 
10



In [33]:
# integreation of p(x)d(x) = 1
# this means
# probability of landing in infimensial region with volume d(x) is given by integration of p(x)d(x) and it dose not give the probability of specific state.

### 3.4 Marginal Probability

#### So This is Marginal Probability v0.01

In [34]:
# How to find the probabilty distribution of a subset of states given a set all possible states.

This is for discrete variable.

In [35]:
sample = 10
dis_random_var_x = torch.randint(sample, (1,),)
dis_random_var_y = torch.randint(sample, (1,),)
print(f"Discrete Random Variable X: {dis_random_var_x}")
print(f"Discrete Random Variable Y: {dis_random_var_y}")

Discrete Random Variable X: tensor([3])
Discrete Random Variable Y: tensor([2])


In [36]:
Range = torch.arange(1, sample+1)

In [37]:
out = []
j = dis_random_var_x
for i in Range:
    if j in i:
        out.append(j)
    else:
        pass

prob1 = len(out) / Range.nelement()
prob1

0.1

In [38]:
out = []
j = dis_random_var_y
for i in Range:
    if j in i:
        out.append(j)
    else:
        pass

prob2 = len(out) / Range.nelement()
prob2

0.1

In [39]:
mar_prob = prob1 + prob2
mar_prob

0.2

This is for Continuous Variable.

In [40]:
# IN PROGRESS

### 3.5 Conditional Probability

In [41]:
start, stop = 1, 11
dis_random_var_x = torch.randint(start, stop, (1,),) 
dis_random_var_y = torch.randint(start, stop, (1,),)
print(f"Discrete Random Variable X: {dis_random_var_x}")
print(f"Discrete Random Variable Y: {dis_random_var_y}")

Discrete Random Variable X: tensor([3])
Discrete Random Variable Y: tensor([4])


In [42]:
ss = torch.arange(start, stop)
ss

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
prob = 0
if dis_random_var_x in ss:
    prob += 1
else:
    None

prob_x = prob / ss.nelement() 

In [44]:
prob_x

0.1

In [45]:
prob = 0
if dis_random_var_y in ss:
    prob += 1
else:
    None

prob_y = prob / ss.nelement()

In [46]:
prob_y

0.1

In [47]:
prob_x_and_y = prob_x + prob_y

In [48]:
prob_y_given_x = prob_x_and_y / prob_x

In [49]:
prob_y_given_x

2.0

In [50]:
# Notes
# Conditional Probability is only defined when the probability of x is greater than 0 (P(x) > 0)
# Intervention query and casual modelling (need exploration here)

### 3.6 The Chain Rule of Conditional Probability

In [51]:
# Chain rule or Product rule of Conditional probability
# P(a, b, c) = P(a | b, c)P(b, c)
# P(b, c) = P(b | c)P(c)
# P(a, b, c) = P(a | b, c)P(b | c)P(c)

### 3.7 Independence and Conditional Independence

Two random variable x and y are independant if their probability distribution can be expressed as a product of two factors,
one involving only x and one involving only y

In [52]:
# P(X = x, Y = y) = P(X = x)P(Y = y)
# event x doesn't influence event y, they are independent.

Two random variable x and y are conditionally independent given a random variable z if the conditional probability distribution over x and y factorizes in this way for every value of z

In [53]:
# for all X = x, Y = y, Z = z, P(X = x, Y = y | Z = z) = P(X = x | Z = z)P(Y = y | Z = z)
# means that x and y are conditional independent given z

### 3.8 Expectation, Variance and Covariance

In [64]:
dis_var = torch.tensor([1, 2, 3, 4, 4, 4, 3, 2, 1])

In [66]:
unique_values, counts = torch.unique(dis_var, return_counts=True)
unique_values, counts

(tensor([1, 2, 3, 4]), tensor([2, 2, 2, 3]))

In [68]:
total_elements = dis_var.nelement()
prob = counts.float() / total_elements

In [70]:
expectation = torch.sum(unique_values.float() * prob)
expectation

tensor(2.6667)

In [71]:
print(f"Expected value (E[x]) of dis_var: {expectation.item()}")

Expected value (E[x]) of dis_var: 2.6666667461395264


### 3.9 Comman Probability Distribution

#### 3.9.1 Bernoulli Distribution

#### 3.9.2 Multinoulli Distribution

#### 3.9.3 Gaussian Distribution

#### 3.9.4 Exponential and Laplace Distribution

#### 3.9.5 The Dirac Distribution and Empirical Distribution

#### 3.9.6 Mixture of Distributions

### 3.10 Useful Properties of Comman Functions

### 3.11 Bayes' Rule

### 3.12 Technical Details of Continuous Variables

### 3.13 Information Theory

### 3.14 Structured Probabilistic Models