In [2]:
import numpy
import plotly.express as px
import torch
import matplotlib.pyplot as plt
%matplotlib inline

### 3.3 Probability Distribution

#### 3.3.1 Discreate Variable and Probability Mass Function

In [19]:
dis_var = torch.tensor([0, 1, 1, 2, 3, 4, 5, 6, 7, 8])
dis_var, dis_var.nelement()

(tensor([0, 1, 1, 2, 3, 4, 5, 6, 7, 8]), 10)

In [20]:
# Probability Distribution over discreate variable is called Probability Mass Function
# Mainly Denoted by P(x = x) | P(x) and P(y = y) | P(y) and P(x=x, y=y) == P(x, y)
# 1) P(x = x) = 1 means x is certain.  2) P(x = x) = 0 means is impossible.

In [33]:
total = []
i = 1
for j in dis_var:
    if i in j:
        total.append(i)
    else:
        pass
prob = len(total) / dis_var.nelement()
if prob < 0.0:
    raise ValueError("Probability of 0 has impossible event")
elif prob > 1.0:
    raise ValueError("Probability of greater than 1 has out of state of event.")
else:
    prob
print(prob)

0.2


In [35]:
# 1) single discrete random variable x with k different states. We can place a uniform distribution over x.
# 2) the Probability Mass Function is 1 / k = P(x = x_i) for all i. (k is positive integer)
# 3) sum(P(x = x_i)) == sum(1 / k) == k / k == 1 the distribution is properly normalised.

In [37]:
one = 1
x = torch.arange(10)
k = x.nelement()
prob_mass_func = one / k
prob_mass_func

0.1

In [38]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
k / k

1.0

In [46]:
probs = []
for i in x:
    j = i.nelement()
    probs.append(j / k)
    
probs = torch.tensor(probs)
print(probs[0]) # ----------------------- 2) PMF
torch.sum(probs) # ---------------------- 3) normalised to one

tensor(0.1000)


tensor(1.0000)

#### 3.3.2 Continous Variable and Probability Density Function

In [51]:
# On continous random variables we discribe the probability distribution using probability density function rather than Probability Mass Function.
# the domain of P must be all possible states of x

In [52]:
con_var = torch.arange(10, dtype=torch.float32)
con_var

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
# so the p(x) >= 0. Note that we do not require p(x) <= 1
k = con_var.nelement()
# x / k must require greater value than 0 and not limited to 1 it can be greater than 1.
print(f"All possible states in con_var:\n {con_var}\n")
print(f"Number of all possible states in con_var: \n{con_var.nelement()}\n")

All possible states in con_var:
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Number of all possible states in con_var: 
10



In [63]:
# integreation of p(x)d(x) = 1
# this means
# probability of landing in infimensial region with volume d(x) is given by integration of p(x)d(x) and it dose not give the probability of specific state.

### Marginal Probability

In [64]:
# How to find the probabilty distribution of a subset of states given a set all possible states.